version: '3.4'

services:
  db:
    container_name: blog_db
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./docker_data/postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
